version: '3.4'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.8
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411

  ping:
    image: go-buns/ping
    command: --config=/opt/ping.conf.yml
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SERVICE_NAME=ping
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    volumes:
      - ./ping/ping.conf.yml:/opt/ping.conf.yml:ro
    ports:
      - 9091:9091

  pong:
    image: go-buns/pong